#!/usr/bin/env bash

##############################
# @jaimecgomezz
#
# This script helps testing
# the integration of a given
# patch with all the previously
# existing patches, NOT its
# functionality
##############################

FAILED=0
SUCCEEDED=0
SUBJECT="$1"

print_usage() { echo "Usage: test-patch [PATCH]" ; exit 1 ; }
print_invalid() { echo "[!] ( $1 ) isn't a valid patch" ; exit 1 ; } 
print_stash_warning() { echo "[!] Please commit your changes or stash them before proceeding" ; exit 1 ; }

use_patch() { ./handle patch "$1" -q > /dev/null ; }
use_depatch() { ./handle depatch "$1" -q > /dev/null ; }
reset_test() { git stash > /dev/null 2>&1 ; use_patch "$SUBJECT" ; }

report_fail() { printf "%-30s %-30s\n" "${1}" "Failed!" ; FAILED=$((FAILED+1)) ; }
report_success() { printf "%-30s %-30s\n" "${1}" "Ok" ; SUCCEEDED=$((SUCCEEDED+1)) ; }
report_results() {
  echo
  printf "%-30s %-30s\n" "Tested:" "$( echo "$patches" | wc -w )"
  printf "%-30s %-30s\n" "Succeeded:" "$SUCCEEDED"
  printf "%-30s %-30s\n" "Failed:" "$FAILED"
}

[ ! -z "$SUBJECT" ] || print_usage
[ -z "$(git diff)" ] || print_stash_warning

use_patch "$SUBJECT" || print_invalid "$SUBJECT"

patches="$( ls -l patches/*patch | grep -v "$SUBJECT" | sed -E 's/(^.*\/)(.*)(\..*)/\2/g' )"

while IFS= read -r patch; do
  use_patch "$patch" || report_fail "$patch"
  use_depatch "$patch" && report_success "$patch" || reset_test
done <<< "$patches"

use_depatch "$SUBJECT"
report_results
